version: '3.8'

services:
  nginx-42:
    build: ./requirements/nginx
    image: nginx-42
    container_name: nginx-42
    ports:
      - 443:443
    depends_on:
      - wordpress-site
    volumes:
      - wordvol:/var/www/html
    networks:
      - Inception_net
    restart: on-failure

  maria-database:
    build: ./requirements/mariadb
    image: maria-database
    container_name: maria-database
    env_file:
      - .env
    volumes:
      - mariavol:/var/lib/mysql
    networks:
      - Inception_net
    restart: on-failure
    healthcheck:
      test:  [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - .env
    depends_on:
      maria-database:
        condition: service_healthy
    volumes:
      - wordvol:/var/www/html
    networks:
      - Inception_net
    restart: on-failure
  
volumes:
  mariavol:
    name: mariavol
    driver_opts:
      type: none
      device: /home/luis/data/database
      o: bind
  wordvol:
    name: wordvol
    driver_opts:
      type: none
      device: /home/luis/data/wordpress
      o: bind

networks:
  Inception_net:
    name: Inception